set shell=/bin/sh
set viminfo='1000,f1,:1000,/1000
set history=1000
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'
if has('nvim')
    Plugin 'ncm2/ncm2'
    Plugin 'roxma/nvim-yarp'
    Plugin 'ncm2/ncm2-path'
    Plugin 'ncm2/ncm2-go'
    Plugin 'ncm2/ncm2-jedi'
    Plugin 'ncm2/ncm2-tern'
endif
Plugin 'junegunn/rainbow_parentheses.vim'
Plugin 'othree/csscomplete.vim'
Plugin 'Raimondi/delimitMate'
Plugin 'Yggdroot/indentLine'
Plugin 'hail2u/vim-css3-syntax'
Plugin 'majutsushi/tagbar'
Plugin 'othree/html5.vim'
Plugin 'mitsuhiko/vim-jinja'
Plugin 'mhinz/vim-startify'
Plugin 'scrooloose/nerdtree'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'jacoborus/tender.vim'
call vundle#end()            " required
filetype plugin indent on    " required

"------  Visual Options  ------
syntax on
set number
set nowrap
set vb
set ruler
let g:indentLine_conceallevel=0 " don't hide anything
let python_highlight_all = 1
let g:pymode_python = 'python3'

"------  Generic Behavior  ------
set tabstop=4
set shiftwidth=4
set softtabstop=0
set expandtab
set smarttab
set backspace=2
set hidden
set nobackup
set noswapfile
set splitbelow
set splitright
set wildmode=longest,list "makes filename completion similar to bash
filetype indent on
filetype plugin indent on
set autoindent
set laststatus=2

"nvim-completion
inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"

"python options
let g:pymode_lint = 1
let g:pymode_lint_checker = "pyflakes,pep8"
let g:pymode_syntax = 1
let g:pymode_syntax_all = 1
let g:pymode_syntax_indent_errors = g:pymode_syntax_all
let g:pymode_syntax_space_errors = g:pymode_syntax_all
let g:pymode_folding = 0

let g:airline_powerline_fonts=1
let g:airline_theme='tender'
let g:airline#extensions#tabline#enabled = 1

"Syntastic Options
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

"Indent Line Options
let g:indentLine_char = '│'
set list lcs=tab:\│\ 

"-----  Some Key Commands -------
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l
nnoremap <C-e> :NERDTreeToggle<CR>
nnoremap <C-t> :TagbarToggle<CR>

" Makes up and down movement more normal
nnoremap j gj
nnoremap k gk

if has('nvim')
    let $NVIM_TUI_ENABLE_TRUE_COLOR=1
    " ncm2 options
    autocmd BufEnter * call ncm2#enable_for_buffer()
    set completeopt=noinsert,menuone,noselect
endif

" Colorscheme options
set t_Co=256
set t_ut=
colorscheme tender
set mouse=a
