#!/bin/bash

if [ -f $HOME/.dmenurc ]; then
    . $HOME/.dmenurc
else
    DMENU='dmenu -i'
fi

result=`printf "choose program\ngoogle\nchoose music\nchoose wifi\nscreenshot\nnow playing\ntoggle sound\npower options" | eval $DMENU`
case $result in
    choose\ program)
        dmenu_run -i -s 0 -x "$X" -y "$Y" -w "$WIDTH" -l 15 -dim 0.8 -p "Programs: " -fn "$FONT" -nb "$NB" -nf "$NF" -sb "$SB" -sf "$SF"
        ;;
    choose\ music)
        /home/nick/.bin/dmenu_mpd
        ;;
    screenshot)
		/home/nick/.bin/instagram -s 0
        ;;
    choose\ wifi)
        nmcli_dmenu
        ;;
    now\ playing )
        /home/nick/.bin/mpdzen/mpdzen
        ;;
    toggle\ sound )
        /home/nick/.bin/volume -t
        ;;
    power\ options )
        /home/nick/.bin/dmenu_shutdown 
        ;;
    google )
        /home/nick/.bin/dmenu_google
        ;;
    *)
        ;;
    esac
