#!/bin/bash

if [ -f $HOME/.dmenurc ]; then
    . $HOME/.dmenurc
else
    DMENU_VERT='dmenu -i'
fi

result=$(mount | eval $DMENU_VERT -p umount -l 20 | awk '{print $3}')
if [ -n "$result" ]; then
    udiskie-umount "$result" 
fi
