#!/bin/bash

if [ -f $HOME/.dmenurc ]; then
    . $HOME/.dmenurc
else
    DMENU='dmenu -i'
fi

result=`printf "lock\nshutdown\nreboot\nsuspend\nhibernate" | eval $DMENU`
case $result in
    shutdown)
        gksu shutdown -h now
        ;;
    lock)
        xscreensaver-command -lock
        ;;
    reboot)
        gksu reboot
        ;;
    suspend)
		gksu systemctl suspend
        ;;
    hibernate)
        gksu pm-hibernate
        ;;
    *)
        ;;
    esac
