#!/bin/bash

#
# Lists all artists/albums in mpd collections and plays the selected
#

if [ -f $HOME/.dmenurc ]; then
    . $HOME/.dmenurc
fi

artists=$(mpc list Artist | awk '{ print "I: " $0 }')
songs=$(mpc list Title | awk '{ print "S: " $0 }')
albums=$(mpc list Album | awk '{ print "A: " $0 }')
search=$artists"\n"$albums"\n"$songs

result=`echo "$search" | eval $DMENU -p Music`

# User canceled input -> exit
[[ $result == "" ]] && exit 0

mode=`echo $result | cut -c 1`

# Cut leading "I: " or "A: "
result=`echo $result | cut -c 4-`

if [ $mode == "I" ]; then
	# Add artist
    mpc -q clear
    mpc -q findadd artist "$result"
    notify-send "Now playing songs from artist: $result"
    mpc -q play
elif [ $mode == "A" ]; then
	# Add album
    mpc -q clear
    mpc -q findadd album "$result"
    notify-send "Now playing the album $result"
    mpc -q play
else
    mpc search title "$result" | mpc add; 
    mpc play $(mpc playlist | wc -l)
fi
