#!/bin/bash

#
# Lists current mpd playlist in vertical dmenu and plays the selected
#

if [ -f $HOME/.dmenurc ]; then
    . $HOME/.dmenurc
else
    DMENU_VERT='dmenu -i'
fi

song=`mpc playlist --format "[%artist% - %title% (%album%)] | %file%" | eval $DMENU_VERT -p playlist`

# Add trailing numbers and grep it to give mpc an id to play
number=`mpc playlist --format "[%artist% - %title% (%album%)] | %file%" | awk '{print NR, $0}' | grep "$song" | awk '{print $1}'`

# When nothing is selected "$number" will be something like
# "1 2 3 4 5 6 7 8 ...", so we simply test if we have only ONE single number
[[ "$numer" -ge 0 ]] && mpc play "$number"
