#!/bin/sh
# Display an OSD of the current track
osd ()
{
  title=`mpc | head -1 | sed 's/^volume: [0-9]*%.*/(nothing)/'`
  [ "$title" = "(nothing)" ] && exit || echo $title
}
pid=`ps ax | grep osd_cat | sed '/grep/d' | awk '{print $1}'`
[ "$pid" ] && kill $pid
echo -e "`osd`" | osd_cat -O 1 -s 2 -S '#999999' -c '#0088CC' -f '-*-envy code r-bold-r-*-*-36-*-*-*-*-*-*-*' -p bottom -A center -d 4
