#!/bin/bash
source $(dirname $0)/panel.cfg

# WIFI ICONS
# 

QUAL=`iwconfig wlp4s0 | grep 'Link Quality=' | awk '{gsub(/[=/]/," "); print $3}'`
MAX=`iwconfig wlp4s0 | grep 'Link Quality=' | awk '{gsub(/[=/]/," "); print $4}'`
PERC=`echo $QUAL*100/$MAX | bc`

icon=""
case $PERC in
	[0-4])
		icon=""
	;;
	[4-9])
		icon=""
	;;
	[2-3]*)
		icon=""
	;;
	[4-5]*)
		icon=""
	;;
	[6-7]*)
		icon=""
	;;
	*)
		icon=""
	;;
esac

echo "%{F$ICON_FG}$icon%{F-}"
