#!/bin/bash
#
# volume - dzen volume bar
#

. ~/dotfiles/.config/bspwm/panel.cfg
. ~/dotfiles/.config/xy_conf

#Customize this stuff
IF="Master"         # audio channel: Master|PCM
SECS="1"            # sleep $SECS
BG="#$BOLDER_BLACK"        # background colour of window
FG="#$WHITE"        # foreground colour of text/icon
BAR_FG="#616161"    # foreground colour of volume bar
BAR_BG="#111111"    # background colour of volume bar
HEIGHT="25"         # window height
WIDTH="220"         # window width
XPOS=$(($MAIN_X+$MAIN_MONITOR_W-$WIDTH))         # horizontal positioning
YPOS=$((($MAIN_Y / 2)-95))           # vertical positioning
BAR_WIDTH="180"     # width of volume bar
ICON=~/.config/bspwm/images/spkr_01.xbm
FONT="-*-clean-*-*-*-*-*-*-*-*-*-*-*-*"
ICON_VOL=~/.config/bspwm/images/spkr_02.xbm
ICON_VOL_MUTE=~/.config/bspwm/images/volume0.xbm
ICON=ICON_VOL

#Probably do not customize
PIPE="/tmp/dvolpipe"

err() {
  echo "$1"
  exit 1
}

usage() {
  echo "usage: dvol [option] [argument]"
  echo
  echo "Options:"
  echo "     -i, --increase - increase volume by \`argument'"
  echo "     -d, --decrease - decrease volume by \`argument'"
  echo "     -n, --notify   - display without any change"
  echo "     -t, --toggle   - toggle mute on and off"
  echo "     -h, --help     - display this"
  exit 
}   
    
#Argument Parsing
case "$1" in 
  '-i'|'--increase')
    [ -z "$2" ] && err "No argument specified for increase."
    [ -n "$(tr -d [0-9] <<<$2)" ] && err "The argument needs to be an integer."
    AMIXARG="${2}%+"
    ;;
  '-d'|'--decrease')
    [ -z "$2" ] && err "No argument specified for decrease."
    [ -n "$(tr -d [0-9] <<<$2)" ] && err "The argument needs to be an integer."
    AMIXARG="${2}%-"
    ;;
  '-t'|'--toggle')
    AMIXARG="toggle"
    ;;
  '-n'|'--notify')
    #Don't increase, just display volumebar
    AMIXARG="0%+"
    ;;
  ''|'-h'|'--help')
    usage
    ;;
  *)
    err "Unrecognized option \`$1', see dvol --help"
    ;;
esac

#Actual volume changing (readability low)
AMIXOUT="$(amixer set "$IF" "$AMIXARG" | tail -n 1)"
MUTE="$(cut -d '[' -f 4 <<<"$AMIXOUT")"
VOL="$(cut -d '[' -f 2 <<<"$AMIXOUT" | sed 's/%.*//g')"
if [ "$MUTE" = "off]" ]; then
  ICON=$ICON_VOL_MUTE
  FG="#111111"
else
  FG="#616161"
  ICON=$ICON_VOL
fi

#Using named pipe to determine whether previous call still exists
#Also prevents multiple volume bar instances
if [ ! -e "$PIPE" ]; then
  mkfifo "$PIPE"
  (dzen2 -tw "$WIDTH" -h "$HEIGHT" -x "$XPOS" -y "$YPOS" -fn "$FONT" -bg "$BG" -fg "$FG" < "$PIPE"
   rm -f "$PIPE") &
fi

#Feed the pipe!
(echo "$VOL" | gdbar -l "^i(${ICON})" -fg "$BAR_FG" -bg "$BAR_BG" -w "$BAR_WIDTH" ; sleep "$SECS") > "$PIPE"
