#! /bin/sh

i=1
for monitor in $(bspc query -M); do
bspc monitor $monitor \
        -n "$i" \
        -d {•,•}
        #-d $i/{I,II}
    let i++
done
NMON=$i
unset i

bspc config border_width       10
bspc config window_gap         12

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true

bspc config adaptative_raise true
#bspc config focused_border_color "#334D24"
#bspc config normal_border_color "#000000"

#bspc config normal_frame_opacity 0.6
#bspc config focused_frame_opacity 0.6

bspc rule -a Feh floating=true center=true
bspc rule -a magic floating=true center=true #Floating terminal
bspc rule -a Nitrogen floating=true center=true
bspc rule -a Screenkey --unmanage
bspc rule -a Gcolor2 floating=true center=true
bspc rule -a Lxappearance floating=true center=true
bspc rule -a Viewnior floating=true center=true
bspc rule -a Feh floating=true center=true
bspc rule -a File-roller floating=true center=true
bspc rule -a Steam floating=true 


bspc config top_padding 20

PANEL_HEIGHT=20
PANEL_FIFO="/tmp/panel-fifo"
#PANEL_FONT="DejaVu Sans Mono:size=9"
 
trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

killall bspwmstatus dzen2 bspc xtitle
[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &
conky -c $HOME/.config/bspwm/conkyrc > "$PANEL_FIFO" &

. panel_colors
FONT_FAMILY='Amble'
FONT_SIZE=11
cat "$PANEL_FIFO" | /home/nick/.config/bspwm/panel_dzen2 -f "$FONT_FAMILY" -s "$FONT_SIZE" | dzen2 -xs 1 -x 5 -y 5 -w 1910 -h $PANEL_HEIGHT -dock -ta l -title-name panel -fn "${FONT_FAMILY}:pixelsize=${FONT_SIZE}" -fg "$COLOR_FOREGROUND" -bg "$COLOR_BACKGROUND" &
wait

#/home/nick/dotfiles/.config/bspwm/panel
 
