#! /bin/sh

i=1
for monitor in $(bspc query -M); do
bspc monitor $monitor \
        -n "$i" \
        -d $i/{I,II}
    let i++
done
NMON=$i
unset i

bspc config border_width       2
bspc config window_gap         12

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true

bspc config adaptative_raise true
bspc config focused_border_color "#334D24"
bspc config normal_border_color "#000000"

bspc config normal_frame_opacity 0.6
bspc config focused_frame_opacity 0.6

bspc rule -a Feh floating=true center=true
bspc rule -a magic floating=true center=true #Floating terminal
bspc rule -a Screenkey --unmanage
bspc rule -a Gcolor2 floating=true center=true
bspc rule -a Lxappearance floating=true center=true
bspc rule -a Viewnior floating=true center=true
bspc rule -a Feh floating=true center=true
bspc rule -a File-roller floating=true center=true
bspc rule -a Steam desktop=3/I

#PANEL_HEIGHT=16
#PANEL_FIFO="/tmp/panel-fifo"
#PANEL_FONT="DejaVu Sans Mono:size=9"
 
#bspc config top_padding $PANEL_HEIGHT
#killall bspwmstatus dzen2 bspc xtitle
#[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
#mkfifo "$PANEL_FIFO"
#bspc control --subscribe > "$PANEL_FIFO" &
#xtitle -sf 'T%s' > "$PANEL_FIFO" &  # Optional: for window title
#bspwmstatus | dzen2 -fn "$PANEL_FONT" -h $PANEL_HEIGHT -ta l &
 
panel
 
