#! /bin/sh
#
# Example panel for LemonBoy's bar

source ~/.config/bspwm/panel.cfg

if [ "$(screenfetch -n | grep 'bspwm')" != "" ]; then
    num_mon=$(bspc query -M | wc -l)a
fi

nowplaying() {
    cur=`mpc current`
    # this line allow to choose whether the output will scroll or not
    test "$1" = "scroll" && PARSER='skroll -n20 -d0.5 -r' || PARSER='cat'
    test -n "$cur" && $PARSER <<< $cur || echo "%{F$ICON_FG}No Music Playing%{F-}"
}

#For on laptop (Commented out for desktop)
#battery() {
#    BATC=/sys/class/power_supply/BAT1/capacity
#    BATS=/sys/class/power_supply/BAT1/status
#
#    test "`cat $BATS`" = "Charging" && echo -n '+' || echo -n '-'
#
#    sed -n p $BATC
#}

while read -r line ; do
	case $line in
		S*) 
            music="%{A:/home/nick/.bin/mpdzen/mpdzen:}%{F$ICON_FG}${MUSIC}%{F-} $(nowplaying)%{A}"
			vol=`amixer sget Master | sed -n "0,/.*\[\([0-9]\+\)%\].*/s//\1/p"`
			wifissid=`if [[ $(iwgetid -r) == "" ]]; then echo -e "Wifi Down"; else iwgetid -r; fi`
			wifistr=`panel_wifi`
			clk=`date "+%I:%M %p" `
			#bat="%{F$ICON_FG}Bat:%{F-} $(battery)"
			sys_infos="%{A:/home/nick/.bin/volume -n:}%{F$ICON_FG}${SOUNDIC} %{F$TEXT_FG}${vol}%%%{A} :: %{F$ICON_FG}${wifistr}%{F$TEXT_FG} ${wifissid} :: %{F$ICON_FG}%{A:/home/nick/.bin/dzen-cal.sh:}${CLKIC} %{F$TEXT_FG}${clk} %{A}%{B-}"
        	;;
		T*)
			# xtitle output
			title="%{F$TITLE_FG}%{B$TITLE_BG} ${line#?} %{B-}%{F-}"
			;;
		W*)
			# bspwm internal state
			wm_infos=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					O*)
						# focused occupied desktop
						wm_infos="${wm_infos}%{F$FOCUSED_OCCUPIED_FG}%{B$FOCUSED_OCCUPIED_BG}%{U$UNDERLINE}%{+u} %{A:bspc desktop ${name} --focus:}+ %{-u}%{B-}%{F-}%{U-}%{A}"
						;;
					F*)
						# focused free desktop
						wm_infos="${wm_infos}%{F$FOCUSED_FREE_FG}%{B$FOCUSED_FREE_BG}%{U$UNDERLINE}%{+u} %{A:bspc desktop ${name} --focus:}- %{-u}%{B-}%{F-}%{A}"
						;;
					U*)
						# focused urgent desktop
						wm_infos="${wm_infos}%{F$FOCUSED_URGENT_FG}%{B$FOCUSED_URGENT_BG}%{U$UNDERLINE}%{+u} %{A:bspc desktop ${name} --focus:}- %{-u}%{B-}%{F-}%{A}"
						;;
					o*)
						# occupied desktop
						wm_infos="${wm_infos}%{F$OCCUPIED_FG}%{B$OCCUPIED_BG} %{A:bspc desktop ${name} --focus:}+ %{B-}%{F-}%{A}"
						;;
					f*)
						# free desktop
						wm_infos="${wm_infos}%{F$FREE_FG}%{B$FREE_BG} %{A:bspc desktop ${name} --focus:}- %{B-}%{F-}%{A}"
						;;
					u*)
						# urgent desktop
						wm_infos="${wm_infos}%{F$URGENT_FG}%{B$URGENT_BG} %{A:bspc desktop ${name} --focus:}- %{B-}%{F-}%{A}"
						;;
					L*)
						# layout
						wm_infos="$wm_infos%{F$FREE_BG}%{F-}"
						;;
				esac
				shift
			done
			;;
	esac
	printf "%s\n" "%{c}${wm_infos}%{l}${title}%{r}%{B$INFO_BG} ${music} :: ${sys_infos}"
done
