#! /bin/sh

source ~/.config/bspwm/panel.cfg

PANEL_FIFO=/tmp/panel-fifo
PANEL_HEIGHT=18
FONT1="-*-terminus-medium-r-normal-*-12-*-*-*-c-*-*-1"
FONT2="-misc-stlarch-medium-r-normal--10-100-75-75-c-80-iso10646-1"
export PANEL_FIFO PANEL_HEIGHT PANEL_FONT_FAMILY

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &
#conky -c ~/.config/bspwm/conkyrc > "$PANEL_FIFO" &
clock -sf 'S%I:%M %p' > "$PANEL_FIFO" &

cat "$PANEL_FIFO" \
    | panel_bar \
    | bar \
        -g 1905x$PANEL_HEIGHT+1085+5\
        -f "$FONT1","$FONT2"\
        -F "$FOREGROUND"\
        -B "$BACKGROUND" -u 0 &

wait
