#! /bin/sh

source $HOME/dotfiles/.config/bspwm/panel.cfg
. $HOME/dotfiles/.config/xy_conf

PANEL_FIFO=/tmp/panel-fifo
PANEL_HEIGHT=22
FONT1="-*-terminus-medium-r-normal-*-12-*-*-*-c-*-*-1"
FONT2="-misc-stlarch-medium-r-normal--10-100-75-75-c-80-iso10646-1"

export PANEL_FIFO PANEL_HEIGHT PANEL_FONT_FAMILY

if [ $(pgrep -cx panel) -gt 1 ] ; then
    echo "Panel already running"
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"


if [ "$(screenfetch -n | grep 'bspwm')" != "" ]; then
    bspc control --subscribe > "$PANEL_FIFO" &
    xtitle -sf 'T%s' > "$PANEL_FIFO" &
    PANEL_WIDTH="1080"
else 
    #When using 2bwm, I have tint2 running as well. 
    PANEL_WIDTH='800'
fi

#conky -c ~/.config/bspwm/conkyrc > "$PANEL_FIFO" &
clock -sf 'S%I:%M %p' > "$PANEL_FIFO" &

cat "$PANEL_FIFO" \
    | panel_bar \
    | bar -g $(($PANEL_WIDTH+1))x$PANEL_HEIGHT+$((`sres -W`-$PANEL_WIDTH-1)) -f "$FONT1","$FONT2" -b -u "3" -F "$FOREGROUND" -B "$BACKGROUND" | sh & 


wait
